"""Lower recipe IR to a FreeCAD Python macro (source-form target #2).

FreeCAD runs on OCCT, so the semantics match the occt backend; what this
emitter adds is the *source language* angle: the generated .py keeps
parameters as an editable dict and expressions as Python expressions —
open it in FreeCAD (View > Panels > Python console, or run as a macro) and
the model builds natively, still parametric at the script level.

Elements whose slice contains ops FreeCAD's Part API can't express this way
fall back to a comment (none currently — OCCT supports the full dialect).

CLI:  python -m geomir.freecad_script recipes/studio_wall.ir out/model_freecad.py
Verification: syntax is ast-checked in tests; geometry semantics are
verified on a machine with FreeCAD (see docs/VERIFICATION.md §4).
"""

from __future__ import annotations

import sys

from .ir import Module, IRError, parse


class _Emitter:
    def __init__(self, m: Module):
        self.m = m
        self.lines: list[str] = []
        self.n = 0

    def sexpr(self, o) -> str:
        if isinstance(o, (int, float)):
            return repr(float(o))
        if isinstance(o, str) and o.startswith("%"):
            op = self.m.op_producing(o)
            if op.name == "recipe.param":
                return f'P["{op.operands[0]}"]'
            sym = {"expr.add": "+", "expr.sub": "-",
                   "expr.mul": "*", "expr.div": "/"}[op.name]
            return f"({self.sexpr(op.operands[0])} {sym} {self.sexpr(op.operands[1])})"
        raise IRError(f"freecad emit: bad scalar {o!r}")

    def solid(self, ref) -> str:
        """Emit statements computing the solid; return the variable name."""
        op = self.m.op_producing(ref)
        n = op.name
        self.n += 1
        var = f"s{self.n}"
        E = self.sexpr
        if n == "geom.box":
            w, d, h = op.operands
            self.lines.append(f"{var} = Part.makeBox({E(w)}, {E(d)}, {E(h)})")
        elif n == "geom.cylinder":
            r, h = op.operands
            self.lines.append(f"{var} = Part.makeCylinder({E(r)}, {E(h)})")
        elif n == "geom.extrude":
            prof = self.m.op_producing(op.operands[0])
            pts = ", ".join(f"App.Vector({E(p[0])}, {E(p[1])}, 0)"
                            for p in prof.operands[0])
            first = prof.operands[0][0]
            closing = f"App.Vector({E(first[0])}, {E(first[1])}, 0)"
            self.lines.append(
                f"{var} = Part.Face(Part.makePolygon([{pts}, {closing}]))"
                f".extrude(App.Vector(0, 0, {E(op.operands[1])}))")
        elif n == "geom.translate":
            child = self.solid(op.operands[0])
            x, y, z = op.operands[1]
            self.lines.append(f"{var} = {child}.translated("
                              f"App.Vector({E(x)}, {E(y)}, {E(z)}))")
        elif n == "geom.rotate_z":
            child = self.solid(op.operands[0])
            self.lines.append(
                f"{var} = {child}.copy()\n"
                f"{var}.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), "
                f"{E(op.operands[1])})")
        elif n == "geom.union":
            acc = self.solid(op.operands[0])
            for o in op.operands[1:]:
                acc_new = self.solid(o)
                self.n += 1
                nv = f"s{self.n}"
                self.lines.append(f"{nv} = {acc}.fuse({acc_new})")
                acc = nv
            self.lines.append(f"{var} = {acc}")
        elif n == "geom.difference":
            a = self.solid(op.operands[0])
            b = self.solid(op.operands[1])
            self.lines.append(f"{var} = {a}.cut({b})")
        elif n == "geom.intersect":
            acc = self.solid(op.operands[0])
            for o in op.operands[1:]:
                b = self.solid(o)
                self.n += 1
                nv = f"s{self.n}"
                self.lines.append(f"{nv} = {acc}.common({b})")
                acc = nv
            self.lines.append(f"{var} = {acc}")
        elif n == "geom.repeat_x":
            child = self.solid(op.operands[0])
            count, spacing = op.operands[1], op.operands[2]
            self.lines.append(
                f"{var} = {child}\n"
                f"for _i in range(1, int(round({E(count)}))):\n"
                f"    {var} = {var}.fuse({child}.translated("
                f"App.Vector(_i * {E(spacing)}, 0, 0)))")
        elif n == "geom.fillet":
            child = self.solid(op.operands[0])
            self.lines.append(
                f"{var} = {child}.makeFillet({E(op.operands[1])}, "
                f"{child}.Edges)")
        else:
            raise IRError(f"freecad emit: unhandled op {n}")
        return var


def emit_freecad(module: Module) -> str:
    e = _Emitter(module)
    head = [
        f"# FreeCAD macro generated by geomir from recipe.module @{module.name}",
        "# Parameters are live: edit P and re-run the macro.",
        "import FreeCAD as App",
        "import Part",
        "",
        "P = {",
    ]
    for k, v in module.params().items():
        head.append(f'    "{k}": {repr(float(v))},')
    head.append("}")
    head.append("")
    head.append(f'doc = App.newDocument("{module.name}")')
    body = []
    for name, ref in module.exports().items():
        e.lines = []
        var = e.solid(ref)
        role = module.roles().get(name)
        body.append(f"\n# --- element: {name}"
                    + (f"  (role: {role})" if role else ""))
        body.extend(e.lines)
        body.append(f'Part.show({var}, "{name}")')
    tail = ["", "doc.recompute()",
            'print("geomir: built", [o.Name for o in doc.Objects])']
    return "\n".join(head + body + tail) + "\n"


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: python -m geomir.freecad_script <recipe.ir> <out.py>")
    with open(sys.argv[1]) as f:
        module = parse(f.read())
    with open(sys.argv[2], "w") as f:
        f.write(emit_freecad(module))
    print(f"wrote {sys.argv[2]} — open in FreeCAD (Macro > Macros... > Execute)")


if __name__ == "__main__":
    main()
